---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Vincent Allen.
--- DateTime: 12/3/2020 10:32 PM
---

--- Testing github files for LUA on ComputerCraft

for i = 10, 4, 1
do
    print("hi")
end